param([ValidateSet(20)][int]$Count=20)
$ErrorActionPreference='Stop'
$corpusRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$encoding=[Text.UTF8Encoding]::new($false)
function Write-PreservedText([string]$Path,[string]$Text){
    if(Test-Path -LiteralPath $Path){
        if([IO.File]::ReadAllText($Path) -cne $Text){throw "Existing fixture differs; preserve it and create a new version: $Path"}
    }else{[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($Path))|Out-Null;[IO.File]::WriteAllText($Path,$Text,$encoding)}
}
function Tile([string]$Id,[string]$Class='tile',[string]$Text=''){return '<div data-case-node="'+$Id+'" class="'+$Class+'">'+$Text+'</div>'}
$cases=@(
    @{name='solid-box';family='block';features=@('box','solid-fill');css='.box{width:100px;height:100px;background:#2864b4;margin:16px}';html=(Tile 'box' 'box')},
    @{name='fractional-box';family='block';features=@('fractional-sizing','border','padding');css='.box{width:101.5px;height:63.25px;margin:10.5px;padding:7.5px;border:1px solid #d94b30;background:#72b8a4;box-sizing:border-box}';html=(Tile 'box' 'box')},
    @{name='margin-collapse';family='block';features=@('margin-collapse','nested-block','negative-margin');css='.outer{width:240px;margin:24px 12px;background:#d8e6ef}.a{height:40px;margin:18px 0 22px;background:#376996}.b{height:48px;margin:30px 0 -6px;background:#cf8b38}.next{height:20px;width:270px;background:#593960}';html=('<div data-case-node="outer" class="outer">'+(Tile 'a' 'a')+(Tile 'b' 'b')+'</div>'+(Tile 'next' 'next'))},
    @{name='flex-distribution';family='flex';features=@('flex','grow','gap','min-width');css='.row{display:flex;width:301px;height:90px;gap:7px;padding:12px;background:#e0e8f0}.tile{min-width:0;background:#376996;flex:1}.tile:nth-child(2){flex:2;background:#cc6c36}';html=('<div data-case-node="row" class="row">'+(Tile 'a')+(Tile 'b')+(Tile 'c')+'</div>')},
    @{name='flex-wrap';family='flex';features=@('flex','wrap','align-content','border');css='.row{display:flex;flex-wrap:wrap;gap:9px;width:260px;height:190px;align-content:space-between;border:2px solid #26394d;padding:8px}.tile{width:78px;height:42px;background:#519fa1}';html=('<div data-case-node="row" class="row">'+(-join (1..7|ForEach-Object{Tile ('tile'+$_)}))+'</div>')},
    @{name='nested-flex-grid';family='flex';features=@('flex','grid','percentage','nested-sizing');css='.shell{display:flex;gap:10px;padding:12px;width:340px;height:180px;background:#e8eef4}.aside{width:70px;background:#294c70}.main{display:flex;flex-direction:column;flex:1;gap:8px;min-width:0}.header{height:25px;background:#ce743a}.grid{display:grid;grid-template-columns:1fr 2fr;gap:7px;flex:1}.tile{background:#539b8e}';html=('<div data-case-node="shell" class="shell">'+(Tile 'aside' 'aside')+'<div data-case-node="main" class="main">'+(Tile 'header' 'header')+'<div data-case-node="grid" class="grid">'+(Tile 'a')+(Tile 'b')+(Tile 'c')+(Tile 'd')+'</div></div></div>')},
    @{name='grid-tracks';family='grid';features=@('grid','fr','minmax','gap');css='.grid{display:grid;grid-template-columns:70px minmax(40px,1fr) 2fr;grid-template-rows:42px 58px;gap:7px 9px;width:333px;padding:11px;background:#d8e5ec}.tile{background:#427598}.tile:nth-child(even){background:#c58743}';html=('<div data-case-node="grid" class="grid">'+(-join (1..6|ForEach-Object{Tile ('tile'+$_)}))+'</div>')},
    @{name='grid-spanning';family='grid';features=@('grid','span','implicit-track','nested-block');css='.grid{display:grid;grid-template-columns:repeat(3,82px);grid-auto-rows:38px;gap:8px;padding:12px;background:#dde7f0;width:262px}.tile{background:#347c87}.wide{grid-column:span 2;background:#d4863c}.tall{grid-row:span 2;background:#7c5b9a}';html=('<div data-case-node="grid" class="grid">'+(Tile 'a' 'tile wide')+(Tile 'b' 'tile tall')+(Tile 'c')+(Tile 'd')+(Tile 'e')+'</div>')},
    @{name='table-spans';family='table';features=@('table','colspan','rowspan','border-collapse');css='table{width:330px;border-collapse:collapse;table-layout:fixed;margin:12px}td{border:2px solid #253d58;padding:8px;height:34px;background:#93c1ca}td.alt{background:#d9a45c}';html='<table data-case-node="table"><tbody><tr><td data-case-node="a" rowspan="2"></td><td data-case-node="b" colspan="2" class="alt"></td></tr><tr><td data-case-node="c"></td><td data-case-node="d" class="alt"></td></tr><tr><td data-case-node="e" colspan="3"></td></tr></tbody></table>'},
    @{name='position-stacking';family='position';features=@('absolute','z-index','containing-block','opacity');css='.outer{position:relative;width:290px;height:180px;margin:12px;background:#e1e7f0}.a{position:absolute;left:18px;top:22px;width:155px;height:105px;background:#3e8a9a;z-index:2}.b{position:absolute;left:100px;top:65px;width:150px;height:95px;background:#cc6b3d;opacity:.65;z-index:3}.c{position:absolute;right:12px;top:8px;width:65px;height:65px;background:#675294;z-index:1}';html=('<div data-case-node="outer" class="outer">'+(Tile 'a' 'a')+(Tile 'b' 'b')+(Tile 'c' 'c')+'</div>')},
    @{name='nested-overflow';family='position';features=@('overflow-hidden','nested-clip','absolute');css='.outer{width:220px;height:135px;overflow:hidden;margin:15px;background:#d9e8ee;border:3px solid #254365}.inner{position:relative;width:300px;height:180px;margin:17px;background:#479397;overflow:hidden}.tile{position:absolute;left:65px;top:40px;width:260px;height:90px;background:#d88b42}';html=('<div data-case-node="outer" class="outer"><div data-case-node="inner" class="inner">'+(Tile 'tile')+'</div></div>')},
    @{name='radius-gradient';family='paint';features=@('border-radius','gradient','border','shadow');css='.box{width:240px;height:135px;margin:25px;border:3px solid #26415c;border-radius:22px 8px;background:linear-gradient(120deg,#448c9e,#e2bd74);box-shadow:7px 9px 12px #0004}';html=(Tile 'box' 'box')},
    @{name='svg-paint';family='paint';features=@('svg','viewbox','stroke','transform');css='svg{display:block;margin:12px;background:#eef2f7}';html='<svg data-case-node="svg" width="300" height="170" viewBox="0 0 300 170"><rect x="12" y="15" width="115" height="80" fill="#4d98a1"/><circle cx="185" cy="78" r="43" fill="#d49343" stroke="#273e5a" stroke-width="4"/><path d="M20 145 L95 110 L155 145 L265 115" fill="none" stroke="#714f91" stroke-width="7"/></svg>'},
    @{name='generated-boxes';family='cascade';features=@('pseudo-element','content','absolute','cascade');css='.box{position:relative;width:230px;height:130px;margin:15px;background:#dce8ef}.box::before{content:"";display:block;width:80px;height:55px;background:#3c7b94}.box::after{content:"";position:absolute;right:14px;bottom:12px;width:90px;height:45px;background:#d38b43}';html=(Tile 'box' 'box')},
    @{name='variables-layers-nesting';family='cascade';features=@('variables','layer','nesting','grid');css='@layer base,theme;@layer base{.grid{--gap:5px;display:grid;grid-template-columns:100px 140px;gap:var(--gap);padding:12px}.tile{height:45px;background:#3d6c96}}@layer theme{.grid{--gap:9px;&>.tile:nth-child(2){background:#d6954b}}}.tile:nth-child(3){grid-column:span 2}';html=('<div data-case-node="grid" class="grid">'+(Tile 'a')+(Tile 'b')+(Tile 'c')+'</div>')},
    @{name='responsive-grid';family='responsive';features=@('media','grid','flex','viewport-width');css='.shell{display:grid;grid-template-columns:80px 1fr;gap:10px;padding:12px}.aside{background:#416e94;height:130px}.main{display:flex;gap:8px;flex-wrap:wrap}.tile{background:#d89a50;width:90px;height:60px}@media(width>=800px){.shell{grid-template-columns:180px 1fr}.tile{width:150px}}@media(width>=1200px){.main{gap:20px}.tile{width:190px}}';html=('<div data-case-node="shell" class="shell">'+(Tile 'aside' 'aside')+'<div data-case-node="main" class="main">'+(-join (1..5|ForEach-Object{Tile ('tile'+$_)}))+'</div></div>')},
    @{name='latin-inline';family='text';features=@('text','inline','line-height','wrap');css='.text{width:245px;margin:12px;padding:9px;border:1px solid #384e65;background:#eef2f6;font:16px/22px Arial}.mark{color:#a74f2b;font-weight:bold}';html='<div data-case-node="text" class="text">Alpha beta gamma <span data-case-node="mark" class="mark">delta epsilon</span> zeta eta theta. A second sentence wraps.</div>'},
    @{name='mixed-writing';family='text';features=@('text','korean','bidi','white-space');css='.shell{display:grid;grid-template-columns:180px 130px;gap:12px;margin:12px}.text{background:#e5edf3;padding:8px;font:15px/23px "Malgun Gothic"}.rtl{direction:rtl;background:#ecd8b9;font:16px/24px Arial;padding:8px}';html='<div data-case-node="shell" class="shell"><div data-case-node="text" class="text">한글 레이아웃 검증과 Latin text 123. 여러 줄의 문장을 비교합니다.</div><div data-case-node="rtl" class="rtl">abc 123 שלום xyz</div></div>'},
    @{name='form-initial-state';family='cascade';features=@('form','ua-style','checked','disabled');css='.form{padding:15px;display:grid;gap:12px;width:290px}input,select,button{font:14px Arial}.row{display:flex;gap:10px;align-items:center}';html='<div data-case-node="form" class="form"><input data-case-node="input" value="Static input"><select data-case-node="select"><option>First option</option><option selected>Second option</option></select><div data-case-node="row" class="row"><input data-case-node="checkbox" type="checkbox" checked><input data-case-node="disabled" type="checkbox" disabled><button data-case-node="button">Button</button></div></div>'},
    @{name='complex-dashboard';family='integration';features=@('flex','grid','table','text','absolute','clip');css='.dashboard{display:grid;grid-template-columns:72px 1fr;gap:10px;padding:10px}.sidebar{background:#263e59;min-height:330px}.main{min-width:0}.header{display:flex;justify-content:space-between;background:#dae6f0;padding:12px;margin-bottom:10px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.card{position:relative;background:#72adb2;padding:12px;min-width:0;height:85px;overflow:hidden}.card::after{content:"";position:absolute;right:-8px;bottom:-12px;width:55px;height:55px;background:#dbaa5a;border-radius:50%}.content{display:flex;gap:12px;margin-top:12px}.chart{flex:1;display:flex;gap:7px;align-items:flex-end;height:130px;background:#e6eef4;padding:10px}.bar{flex:1;background:#3a7295}.bar:nth-child(1){height:40%}.bar:nth-child(2){height:80%}.bar:nth-child(3){height:65%}.summary{width:80px;background:#d9b77e;padding:8px}';html='<div data-case-node="dashboard" class="dashboard"><aside data-case-node="sidebar" class="sidebar"></aside><main data-case-node="main" class="main"><header data-case-node="header" class="header"><span data-case-node="title">Overview</span><span data-case-node="status">Ready</span></header><section data-case-node="cards" class="cards"><div data-case-node="card1" class="card">Sales</div><div data-case-node="card2" class="card">Orders</div><div data-case-node="card3" class="card">Reports</div></section><section data-case-node="content" class="content"><div data-case-node="chart" class="chart"><div data-case-node="bar1" class="bar"></div><div data-case-node="bar2" class="bar"></div><div data-case-node="bar3" class="bar"></div></div><div data-case-node="summary" class="summary">Totals<br>123</div></section></main></div>'}
)
$manifest=@();$index=0
foreach($case in $cases){
    $index++;$id=('{0:D4}-{1}' -f $index,$case.name);$folder=Join-Path $corpusRoot ('fixtures\'+$id)
    $html='<!doctype html><html lang="en"><head><meta charset="utf-8"><title>'+ $id+'</title><link rel="stylesheet" href="style.css"></head><body data-case-node="body">'+$case.html+'</body></html>'
    $css='body{margin:0;background:#fff;font:16px/20px Arial;color:#17202a}'+"`n"+$case.css+"`n"
    Write-PreservedText (Join-Path $folder 'index.html') $html
    Write-PreservedText (Join-Path $folder 'style.css') $css
    $metadata=[ordered]@{schemaVersion=1;id=$id;stage='pilot';family=$case.family;features=$case.features;seed=20261003;generatorVersion='1.0';scriptless=$true;states=@('initial');viewports=@(@(384,768),@(800,600),@(1280,800));dpi=@(96,144);htmlSha256=(Get-FileHash -LiteralPath (Join-Path $folder 'index.html') -Algorithm SHA256).Hash;cssSha256=(Get-FileHash -LiteralPath (Join-Path $folder 'style.css') -Algorithm SHA256).Hash}
    Write-PreservedText (Join-Path $folder 'case.json') (($metadata|ConvertTo-Json -Depth 8)+"`n")
    $manifest+=$metadata
}
$manifestPath=Join-Path $corpusRoot 'corpus-manifest.json'
Write-PreservedText $manifestPath (([ordered]@{schemaVersion=1;generatorVersion='1.0';seed=20261003;count=$manifest.Count;cases=$manifest}|ConvertTo-Json -Depth 10)+"`n")
Write-Output ('Preserved '+$manifest.Count+' fixtures: '+$manifestPath)
